platform:ios,’8.0’
#use_frameworks!
inhibit_all_warnings!
source 'git@github.com:CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
        end
    end
end

target :'BSBacktraceLogger' do
    pod 'BSBacktraceLogger',  :path => '../'
end
